[package]
name = "trackball"
version = "0.9.0"
authors = ["Rouven Spreckels <rs@qu1x.dev>"]
edition = "2021"
description = "Virtual Trackball Orbiting via the Exponential Map"
documentation = "https://docs.rs/trackball"
repository = "https://github.com/qu1x/trackball"
build = "build.rs"
readme = "README.md"
license = "BSD-2-Clause-Patent"
keywords = [
	"virtual-trackball",
	"exponential-map",
	"quaternion",
	"arcball",
	"camera",
]
categories = [
	"no-std",
	"graphics",
]
include = [
	"src/**/*.rs",
	"c11/src/**/*.[hc]",
	"build.rs",
	"Cargo.toml",
	"README.md",
	"RELEASES.md",
	"LICENSES/*.md",
]

[dependencies]
heapless = { version = "0.7.16", default-features = false }
nalgebra = { version = "0.32.2", default-features = false, features = ["libm-force"] }

[build-dependencies]
cc = { version = "1.0.79", optional = true }
