name: build
on:
  merge_group:
  pull_request:
  push:
env:
  CARGO_TERM_COLOR: always
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: msrv
      run: |
        msrv=$(cargo metadata --no-deps --format-version 1 |
          jq --raw-output '.packages[] | select(.name=="trackball") | .rust_version')
        echo "MSRV=$msrv" >> $GITHUB_ENV
    - name: toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.MSRV }}
        components: rustfmt, rust-docs, clippy
    - name: test
      run: cargo test
    - name: clippy
      run: |
        cargo clippy --tests -- -D clippy::all -D clippy::pedantic -D clippy::nursery
    - name: doc
      run: cargo doc
    - name: fmt
      run: cargo fmt --check
  all-features:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: msrv
      run: |
        msrv=$(cargo metadata --no-deps --format-version 1 |
          jq --raw-output '.packages[] | select(.name=="trackball") | .rust_version')
        echo "MSRV=$msrv" >> $GITHUB_ENV
    - name: toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.MSRV }}
        components: rustfmt, rust-docs, clippy
    - name: test
      run: cargo test --all-features
    - name: clippy
      run: |
        cargo clippy --tests --all-features -- -D clippy::all -D clippy::pedantic -D clippy::nursery
    - name: doc
      run: cargo doc --all-features
    - name: fmt
      run: cargo fmt --check --all-features
  all-features-nightly:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: rustfmt, rust-docs, clippy
    - name: test
      run: cargo test --all-features
    - name: clippy
      run: |
        cargo clippy --tests --all-features -- -D clippy::all -D clippy::pedantic -D clippy::nursery
    - name: doc
      env:
        RUSTDOCFLAGS: --cfg docsrs
      run: cargo doc --all-features
    - name: fmt
      run: cargo fmt --check --all-features
